version: '3'
services:
  frontend:
    build: ./registration-form
    ports:
      - "8080:80"
    container_name: react-frontend
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: react-backend
    restart: always
